services:


  frontend:
    build: ./frontend/Kaiju
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - prisma-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start"
    networks:
      - prisma-network
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
      
        - path: ./backend 
          target: /backend
          action: sync
          ignore: 
            - node_modules/


networks:
  prisma-network:

